server:
  port: 8003

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.yang.springsecurity.entity

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    username: root
    password: 237502
    url: jdbc:mysql://localhost:3306/demo_test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver